# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0E0600)
$foreground = rgb(F4EFEA)
$color0 = rgb(231F1B)
$color1 = rgb(584737)
$color2 = rgb(5A4A3A)
$color3 = rgb(876F3F)
$color4 = rgb(7F7162)
$color5 = rgb(827465)
$color6 = rgb(A89E93)
$color7 = rgb(E7E0D9)
$color8 = rgb(A29D98)
$color9 = rgb(755F4A)
$color10 = rgb(79634E)
$color11 = rgb(B49454)
$color12 = rgb(AA9683)
$color13 = rgb(AD9A87)
$color14 = rgb(E0D2C4)
$color15 = rgb(E7E0D9)
