# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F4EFEA
background         #0E0600
cursor             #B6A99C

active_tab_foreground     #0E0600
active_tab_background     #F4EFEA
inactive_tab_foreground   #F4EFEA
inactive_tab_background   #0E0600

active_border_color   #F4EFEA
inactive_border_color #0E0600
bell_border_color     #584737

color0      #231F1B
color1		#584737
color2		#5A4A3A
color3		#876F3F
color4		#7F7162
color5		#827465
color6		#A89E93
color7		#E7E0D9
color8		#A29D98
color9		#755F4A
color10		#79634E
color11		#B49454
color12		#AA9683
color13		#AD9A87
color14		#E0D2C4
color15		#E7E0D9
